[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "https://blog.veselin.dev/*"
  to = "https://lynn.zone/blog/:splat"
  force = true

[[redirects]]
  from = "https://veselin.dev/*"
  to = "https://lynn.zone/"
  force = true