[build]
  command = "yarn build && yarn build:lambda"
  functions = "lambda-output"

[[redirects]]
  from = "https://blog.veselin.dev/*"
  to = "https://veselin.dev/blog/:splat"

[[redirects]]
  from = "https://blog.veselin.dev/"
  to = "https://veselin.dev/"